In [49]:
import numpy as np
import pandas as pd 

In [50]:
df = pd.read_csv('../../resources/diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [51]:
df["Outcome"].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [52]:
x = df.drop("Outcome", axis=1)
y = df["Outcome"]

In [53]:
x = np.array(x)
y = np.array(y)

In [54]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x = scaler.fit_transform(x)
x

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [55]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.2)

# Decision Tree

In [59]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(max_depth=8, min_samples_split=4, min_samples_leaf=2)
dt.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=8, min_samples_leaf=2, min_samples_split=4)

# Random Forest

In [63]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, max_depth=8)
rf.fit(x_train, y_train)

RandomForestClassifier(max_depth=8)

In [64]:
from sklearn.metrics import accuracy_score

y_pred_train_dt = dt.predict(x_train)
y_pred_train_rf = rf.predict(x_train)

acc_train_dt = accuracy_score(y_train, y_pred_train_dt)
acc_train_rf = accuracy_score(y_train, y_pred_train_rf)

acc_train_dt*100, acc_train_rf*100

(91.53094462540716, 96.90553745928338)

In [65]:
y_pred_test_dt = dt.predict(x_test)
y_pred_test_rf = rf.predict(x_test)

acc_test_dt = accuracy_score(y_test, y_pred_test_dt)
acc_test_rf = accuracy_score(y_test, y_pred_test_rf)

acc_test_dt*100, acc_test_rf*100

(65.5844155844156, 79.22077922077922)

In [67]:
from sklearn.metrics import precision_score, recall_score, confusion_matrix

per_test_dt = precision_score(y_test, y_pred_test_dt)
per_test_rf = precision_score(y_test, y_pred_test_rf)

per_test_dt*100, per_test_rf*100

(54.71698113207547, 74.07407407407408)

In [68]:
rc_test_dt = recall_score(y_test, y_pred_test_dt)
rc_test_rf = recall_score(y_test, y_pred_test_rf)

rc_test_dt*100, rc_test_rf*100

(50.0, 68.96551724137932)

In [69]:
confusion_matrix(y_test, y_pred_test_dt)

array([[72, 24],
       [29, 29]], dtype=int64)

In [70]:
confusion_matrix(y_test, y_pred_test_rf)

array([[82, 14],
       [18, 40]], dtype=int64)