In [1]:
print("hello")

hello


In [1]:
import numpy as np

In [9]:
a = np.array([1, 2, 3, 4]).reshape(-1, 1)
b = np.array([[2, 3, 5], [7, 2, 6]])
print(a.shape, b.shape)
b

(4, 1) (2, 3)


array([[2, 3, 5],
       [7, 2, 6]])

In [26]:
a = np.delete(a, 3, 0)

In [27]:
a.shape
#b = np.vstack((a, b))
#b

(3, 1)

In [33]:
a = a.reshape(1, -1)
b = np.vstack((b, a))
b

array([[2, 3, 5],
       [7, 2, 6],
       [1, 2, 3]])

In [34]:
b.max()

7

In [35]:
b.min()

1

In [36]:
b.mean()

3.4444444444444446

In [37]:
b.std()

1.9499920860871383

In [60]:
b_mean = np.mean(b)
b_std = np.std(b)
b_norm = (b - b_mean) / b_std
print(b_norm)
print(np.mean(b_norm))
print(np.std(b_norm))


[[-0.74074375 -0.22792115  0.79772404]
 [ 1.82336922 -0.74074375  1.31054663]
 [-1.25356634 -0.74074375 -0.22792115]]
-1.0485439677015367e-16
1.0


In [39]:
b_norm

array([[ 0.23361106,  1.23361106,  3.23361106],
       [ 5.23361106,  0.23361106,  4.23361106],
       [-0.76638894,  0.23361106,  1.23361106]])

In [52]:
print(a)
print(b)
a[1:2]

[[1 2 3]]
[[2 3 5]
 [7 2 6]
 [1 2 3]]


array([], shape=(0, 3), dtype=int32)

In [64]:
#Numpy